export enum EventType {
  //Auth
  SIGNIN = 'SIGNIN',
  REGISTER = 'REGISTER',

  //User
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',

  //Role
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',
  ROLE_DUPLICATED = 'ROLE_DUPLICATED',

  //interlocutor
  INTERLOCUTOR_CREATED = 'INTERLOCUTOR_CREATED',
  INTERLOCUTOR_UPDATED = 'INTERLOCUTOR_UPDATED',
  INTERLOCUTOR_DELETED = 'INTERLOCUTOR_DELETED',

  //Bank Account
  BANK_ACCOUNT_CREATED = 'BANK_ACCOUNT_CREATED',
  BANK_ACCOUNT_UPDATED = 'BANK_ACCOUNT_UPDATED',
  BANK_ACCOUNT_DELETED = 'BANK_ACCOUNT_DELETED',

  //Default Condition
  DEFAULT_CONDITION_CREATED = 'DEFAULT_CONDITION_CREATED',
  DEFAULT_CONDITION_UPDATED = 'DEFAULT_CONDITION_UPDATED',
  DEFAULT_CONDITION_MASS_UPDATED = 'DEFAULT_CONDITIONS_UPDATED',
  DEFAULT_CONDITION_DELETED = 'DEFAULT_CONDITION_DELETED',

  //Reference Types
  REF_TYPE_CREATE = 'REF_TYPE_CREATE',
  REF_TYPE_UPDATE = 'REF_TYPE_UPDATE',
  REF_TYPE_DELETE = 'REF_TYPE_DELETE',

  //Reference Parameters
  REF_PARAM_CREATE = 'REF_PARAM_CREATE',
  REF_PARAM_UPDATE = 'REF_PARAM_UPDATE',
  REF_PARAM_DELETE = 'REF_PARAM_DELETE',

  //Enterprise
  ENTERPRISE_CREATED = 'ENTERPRISE_CREATED',
  ENTERPRISE_UPDATED = 'ENTERPRISE_UPDATED',
  ENTERPRISE_DELETED = 'ENTERPRISE_DELETED',

  //Enterprise Member
  ENTERPRISE_MEMBER_CREATED = 'ENTERPRISE_MEMBER_CREATED',
  ENTERPRISE_MEMBER_UPDATED = 'ENTERPRISE_MEMBER_UPDATED',
  ENTERPRISE_MEMBER_DELETED = 'ENTERPRISE_MEMBER_DELETED',

  //Quotation
  QUOTATION_CREATED = 'QUOTATION_CREATED',
  QUOTATION_UPDATED = 'QUOTATION_UPDATED',
  QUOTATION_DELETED = 'QUOTATION_DELETED',
  QUOTATION_DUPLICATED = 'QUOTATION_DUPLICATED',

  //Invoice
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_UPDATED = 'INVOICE_UPDATED',
  INVOICE_DELETED = 'INVOICE_DELETED',
  INVOICE_DUPLICATED = 'INVOICE_DUPLICATED',

  //Payment
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_UPDATED = 'PAYMENT_UPDATED',
  PAYMENT_DELETED = 'PAYMENT_DELETED',

  //Article
  ARTICLE_CREATED = 'ARTICLE_CREATED',
  ARTICLE_UPDATED = 'ARTICLE_UPDATED',
  ARTICLE_DELETED = 'ARTICLE_DELETED',

  //Article Family
  ARTICLE_FAMILY_CREATED = 'ARTICLE_FAMILY_CREATED',
  ARTICLE_FAMILY_UPDATED = 'ARTICLE_FAMILY_UPDATED',
  ARTICLE_FAMILY_DELETED = 'ARTICLE_FAMILY_DELETED',

  //Tax Rate
  TAX_RATE_CREATED = 'TAX_RATE_CREATED',
  TAX_RATE_UPDATED = 'TAX_RATE_UPDATED',
  TAX_RATE_DELETED = 'TAX_RATE_DELETED',

  //Template
  TEMPLATE_CREATED = 'TEMPLATE_CREATED',
  TEMPLATE_UPDATED = 'TEMPLATE_UPDATED',
  TEMPLATE_DELETED = 'TEMPLATE_DELETED',

  //Sequence
  SEQUENCE_UPDATED = 'SEQUENCE_UPDATED'
}
